# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Donderbus < Formula
  desc "Donderbus assigns a PR to a random set of individuals from a GitHub team."
  homepage "https://github.com/slewiskelly/donderbus"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slewiskelly/donderbus/releases/download/v0.1.0/donderbus_0.1.0_darwin_amd64.tar.gz"
      sha256 "441255494f0a830dcaa2914126b82108d14e333c0d3427328f029b17b7342753"

      def install
        bin.install "donderbus"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slewiskelly/donderbus/releases/download/v0.1.0/donderbus_0.1.0_darwin_arm64.tar.gz"
      sha256 "42f680aebe034eae61371139e4a0d45a359e13b5a17c99ff7436838755c63594"

      def install
        bin.install "donderbus"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/slewiskelly/donderbus/releases/download/v0.1.0/donderbus_0.1.0_linux_amd64.tar.gz"
      sha256 "78c05bce5ec2a25ca8e0f11a4283f84c474185f6b557b60a8706f6bf9be8f8eb"
      def install
        bin.install "donderbus"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/slewiskelly/donderbus/releases/download/v0.1.0/donderbus_0.1.0_linux_arm64.tar.gz"
      sha256 "82ede1899963397eb2865fa3c037522fa9bd78757aa5a493c48df1819d02c27e"
      def install
        bin.install "donderbus"
      end
    end
  end

  test do
    donderbus version
  end
end
