# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ock < Formula
  desc "A tool for querying and validating document metadata."
  homepage "https://github.com/slewiskelly/ock"
  version "0.1.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slewiskelly/ock/releases/download/v0.1.0/ock_0.1.0_darwin_amd64.tar.gz"
      sha256 "f079580db13b8dc92a93dbbc630cc6886b90422955de98b6aaa56914d0661b48"

      def install
        bin.install "ock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slewiskelly/ock/releases/download/v0.1.0/ock_0.1.0_darwin_arm64.tar.gz"
      sha256 "e6c53bf9859035bbc008ba7ff978a45c4d81d7a20243dc866499b8f5b0765ee3"

      def install
        bin.install "ock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/slewiskelly/ock/releases/download/v0.1.0/ock_0.1.0_linux_amd64.tar.gz"
        sha256 "b74a3b88afd24b53668fad5d00de382a5aa4d306af428f4055cccfdd6b72e793"

        def install
          bin.install "ock"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/slewiskelly/ock/releases/download/v0.1.0/ock_0.1.0_linux_arm64.tar.gz"
        sha256 "5db6984a38ed1231b84d929897f0e6340821af53579087842881f8f7644d535e"

        def install
          bin.install "ock"
        end
      end
    end
  end

  test do
    ock version
  end
end
