# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ock < Formula
  desc "A tool for querying and validating document metadata."
  homepage "https://github.com/slewiskelly/ock"
  version "0.1.1"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slewiskelly/ock/releases/download/v0.1.1/ock_0.1.1_darwin_amd64.tar.gz"
      sha256 "94ee603623a09cd63ed0e8a3bfb2a6ca11a7673954e43f703205ff1e02732357"

      def install
        bin.install "ock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slewiskelly/ock/releases/download/v0.1.1/ock_0.1.1_darwin_arm64.tar.gz"
      sha256 "89181a5261c440cc2a0a1118e18b2c07d4b035c289ae5b2c00deb6eab07d3f54"

      def install
        bin.install "ock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/slewiskelly/ock/releases/download/v0.1.1/ock_0.1.1_linux_amd64.tar.gz"
        sha256 "82fb14575d6e2200032f3f17a45c5da5f01dc36e4309ddfc02a9b5d7fc7c90f1"

        def install
          bin.install "ock"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/slewiskelly/ock/releases/download/v0.1.1/ock_0.1.1_linux_arm64.tar.gz"
        sha256 "103700b69c4afc76d925ed60ac9cd8e5d2774d13da9a7fea21426a06dccc56cb"

        def install
          bin.install "ock"
        end
      end
    end
  end

  test do
    ock version
  end
end
