# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ock < Formula
  desc "A tool for querying and validating document metadata."
  homepage "https://github.com/slewiskelly/ock"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/slewiskelly/ock/releases/download/v0.1.2/ock_0.1.2_darwin_amd64.tar.gz"
      sha256 "6cfbbe8dfeeff7dbb0ec67f0e24eff7ce646d58c10751df6fa5e09ef07311923"

      def install
        bin.install "ock"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/slewiskelly/ock/releases/download/v0.1.2/ock_0.1.2_darwin_arm64.tar.gz"
      sha256 "f63bbceaf104e7d07186831bf9548f35a4bdfccee878789105387df7cf4b5104"

      def install
        bin.install "ock"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/slewiskelly/ock/releases/download/v0.1.2/ock_0.1.2_linux_amd64.tar.gz"
        sha256 "7fa446aba74054db56d23e898063941023c000e0d4ae4fc7ca133d431474f523"

        def install
          bin.install "ock"
        end
      end
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
        url "https://github.com/slewiskelly/ock/releases/download/v0.1.2/ock_0.1.2_linux_arm64.tar.gz"
        sha256 "1540948a003af3e30c8d87327f87105e0eff259aa158ab0b0fb0c9646a716e39"

        def install
          bin.install "ock"
        end
      end
    end
  end

  test do
    ock version
  end
end
